### ISSUE TITLE
gravity gun tweaks

### ISSUE THREAD

**Issue by ashdnazg** [SpringCabal/Gravitas#27]
if you hit ground-> you're pushed back (or pulled)

**Comment by gajop** [comment]
related: https://github.com/SpringCabal/Gravitas/issues/36 + https://github.com/SpringCabal/Gravitas/issues/35

**Comment by gajop** [comment]
Is there any way to make pull and push have different range?
I tried changing it in https://github.com/SpringCabal/Gravitas/commit/fa140b1be1c48958f298024fad654eeb83cc47fb#diff-5b219943e73e96c222b8eb25f0fd459cR19 , but I think it might cause issues with unit not closing in to attack when in push mode.
The issue here is that I think push is normally better than pull. Maybe this could be fixed by reducing push strength in comparison?

**Comment by silentwings** [comment]
Seems all good to me, now.
I think pulling and pushing youself when you misclick you be kinda annoying, although could make a nice game mechanic if some rooms were designed to make use of it.

**Comment by gajop** [comment]
It could be integrated into the jump mechanic imo (but mostly as the
animation for now).
Impulse is kinda full of issues though

2015-04-21 16:58 GMT+09:00 silentwings notifications@github.com:
