### ISSUE TITLE
It's possible to get inside crates

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#63]
Set gravity gun to pull, aim at crate, wait. The crate will fly towards you, hit you, and you end up inside it. You can walk out again.

**Comment by silentwings** [comment]
Barrels and bombs should probably explode, if you do this to them and they hit you, and they should consequently kill you. You can just dodge out the way as they fly past you, which imo makes for a good game mechanic.

**Comment by gajop** [comment]
it might be a bit too drastic if they hit you when you just pull them (or we need to make sure gravity works perfectly); it's quite possible to pull stuff on yourself just by right clicking on stuff
i think they should do 0 dmg instead, and really be used as an asset rather than a possible hindrance (it simplifies balancing and removes the possibility of random deaths happening)

**Comment by silentwings** [comment]
"fixed" by https://github.com/SpringCabal/Gravitas/commit/ff2a74e3e09576c4a69ebca41044ef2fed0ede20
